### ISSUE TITLE
Spell Uses Tracker is changing whenever something is done

### ISSUE THREAD

**Issue by Unikatze** [Rostaen/goblin-slayer-ttrpg#8]
There's an odd bug with the spell Uses tracking. 
If I put in a number of spell uses, say "5", it will instead have 7 boxes. 
If I click one of those boxes to mark a spell has been used, my spell uses changes to 7. If I mark another one, it changed to 9. 
If I deselect one of the boxes, it still increases the spell uses by 2, regardless of what I do. 
[fvtt-Actor-battle-mage-eYtZ2Bzd22035zTP.json](https://github.com/user-attachments/files/16818337/fvtt-Actor-battle-mage-eYtZ2Bzd22035zTP.json)

**Comment by Rostaen** [comment]
I had noticed something similar with my beta group, actual play podcast and videos on YouTube. I'll look into this further. Thanks!

**Comment by Rostaen** [comment]
## Error Report

Every time the Actor.mjs file was updated (making any change on the character sheet), this would update the spell uses amount by the Magical Talent adventurer skill value.

## Fix

Magical Talent has been set up as a skill value and calculated in the GSActorSheet.mjs file where updates are being made. The skill now compares to a flag value and only updates when the skill is updated.
