### ISSUE TITLE
[Minor] In the compendium packs, the Non-Player Characters is misspelled as "Non-Prayer Characters"

### ISSUE THREAD

**Issue by Unikatze** [Rostaen/goblin-slayer-ttrpg#9]

**Comment by Rostaen** [comment]
This is actually intentional. In the Manga/Anime/Light Novel, the write refers to monsters and anyone that doesn't pray to a god as a "Non-Prayer Character" and people that do as a "Prayer Character". This is a nod in the GS world to PCs and NPCs that we all refer too in our video games.
